name: remote ssh commands
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: 
      name: twitter-clone
      url: https://twitter.arsaizdihar.com
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/code/twitterclone-v2
            git pull
            yarn
            yarn prisma generate
            yarn build
            pm2 restart twitter